### PR TITLE
Implement wasm build scripts with small scaffold

### PR DESCRIPTION
**Pull request by Salzian**
The setup function is copy paste from the 3d example scene and will be replaced with the actual game obviously.

Use `just build` to build the project, then open `dist/index.html` to view the game in browser. You may require a small web server, I used IntelliJs built-in web server.

### CODE REVIEW

**Comment by itsabdelrahman** [comment]
Nice!

Small problem: `just build` fails locally:

Screenshot 2022-11-10 at 18 02 13

<details>
<summary>Output</summary>

```
$ just build
cargo build --release --target wasm32-unknown-unknown
  Downloaded slotmap v1.0.6
  Downloaded wasm-bindgen-shared v0.2.83
  Downloaded wasm-bindgen-backend v0.2.83
  Downloaded wasm-bindgen-macro v0.2.83
  Downloaded wasm-bindgen-macro-support v0.2.83
  Downloaded wasm-bindgen-futures v0.4.33
  Downloaded wasm-bindgen v0.2.83
  Downloaded web-sys v0.3.60
  Downloaded tracing-wasm v0.2.1
  Downloaded js-sys v0.3.60
  Downloaded console_error_panic_hook v0.1.7
  Downloaded bumpalo v3.11.1
  Downloaded 12 crates (1.7 MB) in 1.01s
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling syn v1.0.103
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling serde_derive v1.0.147
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: Recipe `build` failed on line 8 with exit code 101
```
</details>

`just run-dev` works fine, though 👌 

Screenshot 2022-11-10 at 18 04 10

**Comment by Salzian** [comment]
Follow the instructions of the error 😅

**Comment by itsabdelrahman** [comment]
Fails again with a `sh: wasm-bindgen: command not found` error 😂

**Comment by Salzian** [comment]
> Fails again with a `sh: wasm-bindgen: command not found` error 😂 

OK now I forgot to mention a dependency. Should just install needed dependencies by default or do we leave that to the docs?

`cargo install wasm-bindgen-cli`

**Comment by itsabdelrahman** [comment]
I think we should add `wasm-bindgen-cli` as a dependency in the `Cargo.toml` file 🤔

**Comment by itsabdelrahman** [comment]
Ah, got it 👌

**Review by itsabdelrahman — APPROVED** [review]

**Pull request merged**
